[package]
name = "private_perp"
version = "0.1.0"
authors = [""]
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.3.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.9.1" }




