[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perpl_anchor = "zkNRFg6rNJGMqkAYxW1o5sdDSfxqskL1PDbJ4VZ4Zmk"

[programs.devnet]
perpl_anchor = "zkNRFg6rNJGMqkAYxW1o5sdDSfxqskL1PDbJ4VZ4Zmk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet-us.magicblock.app"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[hooks]
